"""Type stubs for anyver."""

from collections.abc import Iterable
from typing import Any, Union

__version__: str

VersionLike = Union["Version", str]
"""Any value accepted where a version is expected: a Version object or a str."""

class Version:
    """A parsed, comparable version string.

    Equality and ordering strip trailing numeric zeros (so `1.0 == 1.0.0`)
    and ignore build metadata (`1.0+a == 1.0+b`). Hashable; usable in sets
    and as dict keys.
    """

    def __init__(self, version: str, ecosystem: str = "auto") -> None: ...

    # --- Classmethods / alternative constructors ---
    @classmethod
    def parse(cls, version: str, ecosystem: str = "auto") -> Version:
        """Parse a version string. Raises ValueError for invalid input under
        a non-generic ecosystem."""
    @staticmethod
    def try_parse(version: str, ecosystem: str = "auto") -> Version | None:
        """Parse, returning None if invalid."""
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Version:
        """Reconstruct from the dict produced by `to_dict()`."""

    # --- Properties ---
    @property
    def raw(self) -> str: ...
    @property
    def ecosystem(self) -> str: ...
    @property
    def epoch(self) -> int: ...
    @property
    def build(self) -> str: ...
    @property
    def is_prerelease(self) -> bool: ...
    @property
    def is_postrelease(self) -> bool: ...
    @property
    def is_stable(self) -> bool: ...
    @property
    def count(self) -> int: ...
    @property
    def major(self) -> int: ...
    @property
    def minor(self) -> int: ...
    @property
    def patch(self) -> int: ...

    # --- Sequence protocol ---
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int | str: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Iterable[int | str]: ...

    # --- Comparison ---
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __reduce__(self) -> tuple[Any, tuple[str, str]]: ...

    # --- Methods ---
    def segments(self) -> tuple[int | str, ...]: ...
    def release(self) -> tuple[int, ...]: ...
    def compare(self, other: VersionLike, ecosystem: str | None = ...) -> int: ...
    def to_dict(self) -> dict[str, Any]:
        """Structured representation including `raw`, `ecosystem`, `epoch`,
        `major`/`minor`/`patch`, `build`, and release-type flags."""
    def sort_key(self) -> tuple[tuple[int, int, str], ...]:
        """Database-friendly tuple sort key isomorphic to `anyver.compare`."""

# --- Module-level functions ---

def version(s: str, ecosystem: str = "auto") -> Version: ...
def compare(a: VersionLike, b: VersionLike, ecosystem: str = "generic") -> int: ...
def compare_semver_strict(a: str, b: str) -> int: ...
def sort_versions(
    versions: Iterable[VersionLike], ecosystem: str = "generic"
) -> list[VersionLike]: ...
def batch_compare(
    pairs: Iterable[tuple[VersionLike, VersionLike]], ecosystem: str = "generic"
) -> list[int]: ...
def max_version(versions: Iterable[VersionLike], ecosystem: str = "generic") -> VersionLike: ...
def min_version(versions: Iterable[VersionLike], ecosystem: str = "generic") -> VersionLike: ...
def stable_versions(
    versions: Iterable[VersionLike], ecosystem: str = "generic"
) -> list[VersionLike]: ...
def latest_stable(versions: Iterable[VersionLike], ecosystem: str = "generic") -> VersionLike: ...

# --- Boolean helpers (str-only for speed) ---
def gt(a: str, b: str, ecosystem: str = "generic") -> bool: ...
def ge(a: str, b: str, ecosystem: str = "generic") -> bool: ...
def gte(a: str, b: str, ecosystem: str = "generic") -> bool: ...
def lt(a: str, b: str, ecosystem: str = "generic") -> bool: ...
def le(a: str, b: str, ecosystem: str = "generic") -> bool: ...
def lte(a: str, b: str, ecosystem: str = "generic") -> bool: ...
def eq(a: str, b: str, ecosystem: str = "generic") -> bool: ...
def ne(a: str, b: str, ecosystem: str = "generic") -> bool: ...

# --- Constraint matching ---
def satisfies(version: str, constraint: str, ecosystem: str = "generic") -> bool:
    """Check whether `version` satisfies `constraint`.

    Supports operators `>=`, `<=`, `>`, `<`, `==`, `!=`, combined with commas
    for AND and `||` for OR. Also supports npm-style shorthand: `^1.2.3`,
    `~1.2`, `1.2.x`, `*`.
    """

# --- Version bumping ---
def bump_major(version: str) -> str: ...
def bump_minor(version: str) -> str: ...
def bump_patch(version: str) -> str: ...
def bump_prerelease(version: str, tag: str = "alpha") -> str:
    """Increment the prerelease counter, or add `-{tag}.0` if absent."""

def next_stable(version: str) -> str:
    """Return the release form of a version, stripping any prerelease tag."""
